function ipsdatosrepu2013 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  IPSDATOSREPU2013 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  IPSDATOSREPU2013 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ipsdatosrepu2013 = importfile("C:\Users\SERGIO\Downloads\sda proy_xavi\sda proy\ASN\ips_datos_repu_2013.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-May-2025 05:34:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["\t", ","];

% Specify column names and types
opts.VariableNames = ["city", "region", "country", "loc", "org", "postal", "timezone", "hostname", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19"];
opts.SelectedVariableNames = ["city", "region", "country", "loc", "org", "postal", "timezone", "hostname"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "categorical", "double", "double", "categorical", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["hostname", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["city", "region", "country", "loc", "timezone", "hostname", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "org", "TrimNonNumeric", true);
opts = setvaropts(opts, "org", "ThousandsSeparator", ",");

% Import the data
ipsdatosrepu2013 = readtable(filename, opts);

end