function arin1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ARIN1 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  ARIN1 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  arin1 = importfile("C:\Users\lucia\MATLAB Drive\SDA\proy\arin.txt", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Mar-2025 13:52:24

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "|";

% Specify column names and types
opts.VariableNames = ["zona", "pais", "tipo", "IP", "cantidadIP", "fecha", "estado", "VarName8"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "string", "double", "datetime", "categorical", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["IP", "VarName8"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["zona", "pais", "tipo", "IP", "estado", "VarName8"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "fecha", "InputFormat", "yyyy-MM-dd", "DatetimeFormat", "preserveinput");

% Import the data
arin1 = readtable(filename, opts);

end