function IndicadoresITU = leerIndicadoresITU(filename, dataLines)
%IMPORTFILE Import data from a text file
%  INDICADORESITU = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  INDICADORESITU = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  IndicadoresITU = importfile("C:\Users\jorge\MATLAB Drive\Proyecto\Indicadores_ITU.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Apr-2024 17:36:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Pais", "Casas_internet", "Casas_ordenador", "Gente_con_internet", "Gente_ordenador", "IXPs", "Poblacion", "ISPs", "Inversion"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Pais", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Pais", "EmptyFieldRule", "auto");

% Import the data
IndicadoresITU = readtable(filename, opts);

end