function fuerzaBruta = leerWire(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FUERZABRUTA = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  FUERZABRUTA = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  fuerzaBruta = importfile("/Users/annagilmoliner/CD 2023:2024/SDA/DRIVE/PROYECTO/fuerzaBruta.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Apr-2024 12:25:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Time", "Source", "Destination", "Protocol", "Length", "Info"];
opts.SelectedVariableNames = ["Time", "Source", "Destination", "Protocol", "Length", "Info"];
opts.VariableTypes = ["string", "datetime", "categorical", "categorical", "categorical", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Source", "Destination", "Protocol", "Info"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Time", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");

% Import the data
fuerzaBruta = readtable(filename, opts);

end