function reputationcopia = leerRepu(filename, dataLines)
%IMPORTFILE Import data from a text file
%  REPUTATIONCOPIA = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  REPUTATIONCOPIA = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  reputationcopia = importfile("C:\Users\USUARIO\Downloads\reputation copia.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Feb-2024 08:57:20

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["#", ","];

% Specify column names and types
opts.VariableNames = ["IP", "Fiabilidad", "Riesgo", "MaliciousHost", "Pais", "Ciudad", "Latitud", "Longitud", "X"];
opts.VariableTypes = ["string", "double", "double", "string", "categorical", "categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "IP", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["IP", "MaliciousHost", "Pais", "Ciudad"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Fiabilidad", "Riesgo", "Latitud", "Longitud", "X"], "ThousandsSeparator", ",");

% Import the data
reputationcopia = readtable(filename, opts);

end